### ISSUE TITLE
Cpu Limit/Quota

### ISSUE THREAD

**Issue by barrachri** [jupyterhub/dockerspawner#136]
I was checking https://github.com/jupyterhub/dockerspawner/blob/master/dockerspawner/dockerspawner.py

There is a `mem_limit` but not a `cpu_limit` or `cpu_quota`.

Is not implemented yet ?

**Comment by Wildcarde** [comment]
I suspect this doesn't work as desired in all instances which is why it's not in here yet. Based on this post:
https://github.com/docker/swarm/issues/475

Unfortunately I've run into the result of this where swarm won't assign more containers to a node than it has cores, even when it could easily be sharing that space without interference.

**Comment by willingc** [comment]
Hi all,

Closing this issue as it's been inactive for several months and it's unclear that it is actionable at the moment due to docker swarm limitations. Thanks! :sunflower:

**Comment by robnagler** [comment]
cpu_limit [has been implemented in our subclass of DockerSpawner](https://github.com/radiasoft/rsdockerspawner/blob/91ce96f8c369d297c8fdabc51d2917553d385fe0/rsdockerspawner/rsdockerspawner.py#L55) using the CFS values cpu_period and cpu_quota. The docker daemon [computes these values from NanoCPUs](https://github.com/moby/moby/blob/ec87479/daemon/daemon_unix.go#L142). It seems to work fine. This sidesteps the problem of trying to use CPUShares.

**Comment by blaza1** [comment]
Would it be possible to re-open this issue to potentially merge Rob's work into the main dockerspawner repo? This feature would be super useful for me. We currently have one user who uses sufficient CPU to render other notebooks inoperable. Everything else in dockerspawner is working great
