### ISSUE TITLE
Add docker_host configurable

### ISSUE THREAD

**Issue by dhirschfeld** [jupyterhub/dockerspawner#152]
It was pretty opaque to me how to actually configure the docker host - pulling it from an undocumented environment variable is a bit like black magic.

Whilst it may be well known on linux that `DOCKER_HOST` is a standard environment variable, at least on Windows 2016 you can't install `docker-machine` and the existence of the that particular env var was news to me!

It would seem to me to be more explicit all around for `docker_host` to be a documented configurable which defaulted to `os.environ['DOCKER_HOST']`

**Comment by dhirschfeld** [comment]
Happy to take a stab at it if it's considered a good idea. It might take a while for me to get around to it though...

**Comment by minrk** [comment]
I'm coming from a clearly non-Windows perspective, but I prefer to minimize deviations between the behavior of DockerSpawner and the docker executable itself. docker-py's `kwargs_from_env` does that nicely, and lets the [existing Docker documentation](https://docs.docker.com/engine/reference/commandline/cli/) be the documentation for configuring how to talk to docker.

If a configurable should be added, I would skip docker_host itself and make a passthrough for `client_kwargs`, so that all of Docker's APIClient constructor kwargs can be specified without having to define a new config trait for each arg the Client can take.

**Comment by dhirschfeld** [comment]
It makes perfect sense to me to have the spawner use the environment variables as default values but I think ideally each environment variable would have a configurable on the class so they could be overridden programmatically. 

That would add a maintenance burden having to track the docker env vars though so I like your suggestion of using a `client_kwargs` passthrough. Whilst I think it would be nice to have it's certainly not particularly urgent/important but I'll leave this open in case I find time to come back to it...

**Comment by zsluedem** [comment]
i think change the host to be configurable should be nice~!
@minrk add the client_kwargs should be nice.
i think the spawner should provide more ways for us to configurable not just one way.

**Comment by dhirschfeld** [comment]
I still think it would be nice to be able to programmatically set any of the docker config but I don't think that outweighs the maintenance consideration so I'm happy for this to be closed as a wontfix.

**Comment by zsluedem** [comment]
i pull a request to set docker client to be configurable.
