### ISSUE TITLE
Dockerfile versioning

### ISSUE THREAD

**Issue by dmvieira** [jupyterhub/dockerspawner#184]
Hey guys, why do you changed all docker tags? I was extending your single-user image with tag 0.7.2. What do you think about build better tag versioning?

**Comment by minrk** [comment]
What sort of versioning did you have in mind? Something like `0.7.2-<stack-hash>`?

In most cases, it's best to use [docker-stacks](https://github.com/jupyter/docker-stacks) directly, which have strict tags that you can use.

The tagging on `jupyterhub/singleuser` is pinned to the version of jupyterhub itself, which is the only versioning that's really important for the singleuser image to work. There shouldn't be anything tied to DockerSpawner in the image.

In fact, I'm working right now on moving the singleuser image building over to the jupyterhub repo, because it shouldn't be tied to any version of this repo. (#187)

**Comment by dmvieira** [comment]
> What sort of versioning did you have in mind? Something like 0.7.2-<stack-hash>?

Yes

> In most cases, it's best to use docker-stacks directly, which have strict tags that you can use.

But I need image 100% compatible with jupyterhub-singleuser

> n fact, I'm working right now on moving the singleuser image building over to the jupyterhub repo, because it shouldn't be tied to any version of this repo. (#187)

Could you please use hash? Is it possible?

**Comment by minrk** [comment]
> But I need image 100% compatible with jupyterhub-singleuser

All docker-stacks are 100% compatible with jupyterhub. The `jupyterhub/singleuser` image does nothing other than ensure a particular version of jupyterhub is installed, so that docker-stacks can be used with versions of JupyterHub other than the current stable version. The jupyterhub/docker-stacks images are hash-tagged and have latest stable jupyterhub installed, so work out of the box with dockerspawner.

> Could you please use hash? Is it possible?

I will investigate combining the stack hash with the jupyter version. It's a bit tricky to combine two versions into one, but I'll try.

It's also useful to note that you don't need to trust upstream projects to tag as you prefer. All docker images always get tags based on their checksum:

    FROM jupyterhub/singleuser@sha256:b17d4badfea69a2082abbb0f3fdcf0fbf0564c05105add38950e301051621ff3

The docker checksum tags are more like git commit hashes, whereas docker 'tags' are more like git branches, which are free to move at any time.

which are guaranteed stable, and upstream cannot change them. We use this to pin the base ubuntu version in our [docker-stacks ourselves](https://github.com/jupyter/docker-stacks/blob/75742278ce341c1418fbcbb755a70983abbbfd6e/base-notebook/Dockerfile#L6)

**Comment by dmvieira** [comment]
Ok... I will see this hash
