### ISSUE TITLE
"Failed to check authorization" show on page when login jupyterhub after switch to dockerspawner

### ISSUE THREAD

**Issue by ppLorins** [jupyterhub/dockerspawner#208]
![errors](https://files.gitter.im/jupyterhub/jupyterhub/z8xH/image.png)
Hi all , I successfully lunched a jupyter-single-server inside a docker container by using docerspawner , when login into jupyterhub the page it shows me "Failed to check authorization" ,after check the container log I found the above errors , have no idea why it gave such errors , looks some token issue. 

Anyone who ever experienced this ?

**Comment by harmon** [comment]
Did you ever get this to work?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

Since this is for an old version of JupyterHub (0.8.1) I'm going to close this one as stale and probably fixed. Feel free to open a new Issue if you are still having this trouble.

Most likely, it is due to a version mismatch between the single-user server and jupyterhub itself. More recent versions of jupyterhub do a better job at checking these and giving informative warnings. My guess is that jupyterhub was running 0.7.x and the single-user server had 0.8.x. I say this because the 405 is likely due to the Hub missing the oauth handlers, which would be true for jupyterhub prior to 0.8.
