### ISSUE TITLE
`exec tini`, command not found

### ISSUE THREAD

**Issue by jkbach** [jupyterhub/dockerspawner#222]
This was originally posted in the [`jupyterhub/jupyterhub` issues](https://github.com/jupyterhub/jupyterhub/issues/1649), but I figure it might be more visible here.

Hi!

Apologies if this is an obvious question, I'm new to both JupyterHub and Docker and having a hard time troubleshooting. I'm working on setting up JupyterHub on a server running CentOS 7. I'm trying to create a new container for each user by following the instructions in this video (timestamp in link) https://youtu.be/gSVvxOchT8Y?t=42m10s

Now, when I try to start my server, I get the following error:
```
[I 2018-03-01 16:13:06.292 JupyterHub app:1581] JupyterHub is now running at https://:443/
[I 2018-03-01 16:13:10.210 JupyterHub dockerspawner:545] Found existing container 'jupyter-jkbach' (id: aa9bac9)
[I 2018-03-01 16:13:10.211 JupyterHub dockerspawner:557] Starting container 'jupyter-jkbach' (id: aa9bac9)
[E 2018-03-01 16:13:10.938 JupyterHub user:427] Unhandled error starting jkbach's server: 400 Client Error: Bad Request ("OCI runtime create failed: container_linux.go:296: starting container process caused "exec: \"tini\": executable file not found in $PATH": unknown")
[E 2018-03-01 16:13:10.975 JupyterHub web:1591] Uncaught exception GET /hub/user/jkbach/ (::ffff:173.250.248.220)
```

My current versions:
- JupyterHub version: 0.8.1
- Docker version: 17.12.0-ce, build c97c6d6

Thanks in advance!

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I'm going to close this one as it's for a particularly old version of JupyterHub and probably fixed.

To resolve this issue, we would need some more information, particularly which exact tagged image is being used and any DockerSpawner configuration. My first guess is that $PATH is not being set correctly in the image. This could have been a bug in docker-stacks which is likely since fixed.

Feel free to open a new Issue if you are still having this trouble.
