### ISSUE TITLE
Can't get dockerspawner to work without Oauth

### ISSUE THREAD

**Issue by arthurlogilab** [jupyterhub/dockerspawner#224]
On a setup when I log in using PAM and I have dockerspawner configured and the jupyterhub is behind an nginx. I get the following error : 

```
Failed to connect to Hub API at 'http://127.0.0.1:8081/hub/api'.  Is the Hub accessible at this URL (from host: d8c345def974)?  Make sure to set c.JupyterHub.hub_ip to an IP accessible to single-user servers if the servers are not on the same host as the Hub.
```

The hub_ip is set to 172.17.0.1, and that seems to be ignored since in the docker instance (I do a docker exec to go there) I see the JUPYTERHUB_API_URL set to http://127.0.0.1:8081/hub/api 

The other thing that bothers me is that I get a redirection to /user/arthur/oauth_callback? eventhough I have not enabled oauth authentication. Again, in the docker instance I have ```JUPYTERHUB_OAUTH_CALLBACK_URL=/user/arthur/oauth_callback``` which seems odd. 

Is it supposed to work with the default PAM auth or is using oAuth a requirement ?

**Comment by minrk** [comment]
You can definitely use JupyterHub with PAMAuth and DockerSpawner. The main thing you need to do for DockerSpawner is to set `c.JupyterHub.hub_ip` to an ip address connectable by containers instead of the default of localhost.

JupyterHub uses OAuth *internally* for how single-user servers authenticate users with the Hub. This is not connected to how the *Hub* might or might not use OAuth to authenticate users with an external service.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

It looks like this issue is resolved. Feel free to open a new Issue if you are still having this trouble.

**Comment by jacobicao** [comment]
I resolved the problem by this setting:
`c.Spawner.environment = {'JUPYTERHUB_API_URL': f'{c.JupyterHub.hub_ip}:{c.JupyterHub.hub_port}' }`
