### ISSUE TITLE
Passing python objects through the spawner to a single-user notebook

### ISSUE THREAD

**Issue by davidbath** [jupyterhub/dockerspawner#227]
Hi there!

This may be a question for jupyterhub or spawners more generally, but as I'm using dockerspawner I was hoping you guys might know the answer. 

I'm passing various pieces of extra information that I can establish at user login time (i.e. Authenticator execution) through into the notebook, and at the moment I'm doing that by overriding the authenticators `pre_spawn_start` method and adding some `spawner.environment` variables. The rest is taken care of by the existing code, and so the environment variables show up in my single-user notebook app.

In an ideal world, I'd like to pass a more complex python object through to the notebook somewhere, rather than simple key/values in the environment of the underlying host. I've tried trawling through the code, but I can't spot a way to pass fairly arbitrary variables through the spawner and into the resulting notebook. A possible alternative is to be able to pass a piece of code that executes at notebook startup (like putting code inside `jupyterhub-config.py`) so I could reconstruct a python object from a number of environment variables.

Does anyone know if there's a pre-defined way of doing this, or could offer me some suggestions of where to look or ask next?

Thanks!

**Comment by minrk** [comment]
An interesting idea! The only universal avenue Spawners have to communicate information to servers is environment variables. DockerSpawner, however, has the additional ability to mount things like volumes (and KubeSpawner has similar avenues such as configmaps). If you want to pass a generic Python object, that means pickling. Due to environment variable max size, a pickle might not fit in an environment variable. Plus, since the Hub environment and user environment are not necessarily the same, pickle isn't guaranteed to work unless you ensure that the same version of the package providing the class definition is in both environments.

My recommendation would be to:

1. First, decide if you really do need to pass full objects. It might be that passing the necessary info to reconstruct the object is more feasible than the serialized object itself. This can be done by serializing simple params in JSON, etc. and then reconstructing objects with code, pulling JSON from a volume or environment variable, or a few dedicated environment variables for the parameters.
2. If you really do need full, arbitrary pickled objects, see if you can dynamically create a volume and store the data there and load it from the mounted volume.
3. If a volume isn't feasible and you still need arbitrary pickled objects, you are going to need to come up with a scheme for chunking a pickle into a *series* of environment variables, and then reconstructing the result on the other side. That's going to be a little messy, but it should work if you need it do.

If these are for the kernel, IPython has 'startup' files, which run code on kernel startup. e.g. if you put in `/etc/ipython/startup/myobjects.py`:

```python
myobject = reconstruct_thing_from_env()
```

Then your users would have `myobject` in their namespace every time they start an IPython kernel.

The notebook server itself also has a `jupyter_notebook_config.py` that runs on launch, like `jupyterhub_config.py`, so you can put code in `/etc/jupyter/jupyter_notebook_config.py`, if that's where it is more appropriate.

**Comment by minrk** [comment]
JupyterHub tries to make very few assumptions about what's being launched. Right now, the only assumption it actually makes is that a webserver starts at an ip:port. As a result, instructing the notebook to run arbitrary code as part of startup is unlikely. However, implementing your idea as a Jupyter notebook extension which is loaded by default in your image, you could achieve approximately this. The only assumption you would be making, then, is that your notebook extension is in user environments (pretty reasonable and also portable). Here's an example:

```python
# myarbitrarycodeextension.py
import os

def load_jupyter_server_extension(app):
    code_keys = sorted(key for key in os.environ if key.startswith("ARBITRARY_CODE_")
    parts = []
    for key in code_keys:
        parts(os.environ.pop(key))
    code = ''.join(parts)
    app.log.debug("Executing arbitrary code: %s", code)
    exec(code)
```

and install this extension by creating the file `/etc/jupyter/jupyter_notebook_config.d/arbitrarycode.json`:

```json
{
  "NotebookApp": {
    "nbserver_extensions": {
      "myarbitrarycodeextension": true
    }
  }
}
```

This will execute arbitrary code (chunked across `ARBITRARY_CODE_01, ARBITRARY_CODE_02`, etc.) in the notebook server process as part of server startup.

I'm not sure that executing arbitrary code from environment variables is a good idea, but using a pattern like this to pass information from the spawner to your notebook servers ought to be handily done via notebook extensions. Putting code in jupyter_notebook_config is another way of achieving a similar result.

**Comment by davidbath** [comment]
Cool! I am also not totally convinced by the pattern of passing things around (especially arbitrary code!) in environment variables - so agree with you there!

So for my later points, I was going with the idea that the other thing we can assume about a single-user notebook is that it can access URLs on the hub as it has to call back to it. So, taking the `nbserver_extension` idea on a bit, not only could that be used to pull longer/bigger/more secret parameters from jupyterhub (much like @betatim tokenrefresher service, and therefore avoid some of the issues with storing sensitive material in the environment) but also a `nbserver_extension` could pull snippets of a `jupyter_notebook_config` from an as-yet-to-be-defined `config-file-service` on the hub. 

Taking that idea one step further, rather than it being an extension, this `config-file-service` provided by the hub could be (optionally) called as part of a single-user-notebook startup - effectively as an additional path to check for config files.  That way changing the way that a notebook behaves could be controlled by maintaining files within the hub environment, and not having to rebuild single-user-notebook images. Perhaps even more important when the feature to allow multiple single-user-servers for the same user - it may be that image is actually the same, but the way the notebook is set up is for a different task. 

Anyway - I didn't mean to distract you on a concept that probably doesn't affect most people! But for sure I agree that a push-model beyond environment variables would make the spawner interfaces too brittle/specific so that's a bad idea :)

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

It looks like this issue is resolved. Feel free to open a new Issue or topic on  [the Jupyter forum](http://discourse.jupyter.org) for more general discussions.
