### ISSUE TITLE
Services not added to Stack 

### ISSUE THREAD

**Issue by belfhi** [jupyterhub/dockerspawner#250]
Hello,
I'm not sure if this is the intended behaviour, but when I deploy JupyterHub (docker stack deploy -c docker-stack.yml jupyterhub) with docker swarm and SwarmSpawner a new service is created for the user's Notebook Server (so far so expected). 
When I delete the stack (docker stack rm jupyterhub) the notebook server service is not deleted. It seems the service is not added to the stack. 
Is there any way to include the users' services to the stack?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

The services are not added to the stack because they are not themselves deployed *by* `docker stack`, they are deployed by jupyterhub making docker API calls. If anyone knows how to use the swarm API to create services associated with an existing stack, we can add that as a feature to SwarmSpawner. I don't know if that's possible, though, or if stack updates would necessarily mean deleting all running servers, which would probably be bad!

**Comment by belfhi** [comment]
No worries, I soon realized that z2jh was a more reasonable way to go and never looked back :)
I've also not used docker swarm since...
