### ISSUE TITLE
How to use -v flag with Dockerspawner and Jupyterhub

### ISSUE THREAD

**Issue by lachlancampbell** [jupyterhub/dockerspawner#252]
I’m currently running a jupyterhub service on Ubuntu VM’s for use in training. I utilise dockerspawner, more specifically systemuserspawner, to generate individual notebook servers. I now want to give some instruction on how to use docker. I read Jérôme Petazzoni’s blog (https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/) on how to use the -v flag to give access to the host docker socket, but I’m unable to implement it as I don’t know where the docker run command is being given. Any advice greatly appreciated.

Some details about my setup:
Host machine is running Ubuntu 16.04
Jupyterhub is version 0.7.2
Docker version 17.12.0-ce, build c97c6d6
Initial notebook image is jupyter/datascience-notebook:82b978b3ceeb

**Comment by minrk** [comment]
This would be `c.DockerSpawner.volumes`, e.g.

```python
c.DockerSpawner.volumes = {'/var/run/docker.sock': '/var/run/docker.sock'}
```

to mount the host docker socket to the same location in the container.

DockerSpawner uses the [Docker Python API](https://docker-py.readthedocs.io/en/stable/), so those are the docs to look at for reference, rather than the `docker run` command-line interface.

**Comment by lachlancampbell** [comment]
Thank you :)
