### ISSUE TITLE
How to start a new Notebook container on the host machine when using Jupyterhub as a docker contianer

### ISSUE THREAD

**Issue by w4230213** [jupyterhub/dockerspawner#253]
For some reason, i must run JPH in a dcoker container, now i use DockerSpawner to creat single-user container.
By using  command like "docker run -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock jupyterhub", when logged in the hub(lcoal:8000), a new nb_container is created on the host machine (by docker ps, and i can enter that container by docker exec -it...everything looks fine), but in browser it doesn't work at all, showed a timeout error.

The new container showed in "docker ps" don't have a host port like '8888-->8888' but only '8888',so i guess it means this single-user container is created but has no host port to access...

Can anyone give me some advise about this?

**Comment by w4230213** [comment]
Problem solved, just simply add '--network xxxxx' to docker run command, it's strange that i've already   wrote it in my jupyterhub_config.py. Like 'c.DockerSpawner.network_name=xxxx' and ‘c.DockerSpawner.extra_host_config={'network_mode':xxxxx}’,but it doesnt'work..

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

It looks like this issue is resolved, but I can add some more information: both jupyterhub *and* single-user servers must be put on the docker network. Setting `c.DockerSpawner.network_name` puts single-user containers on the network, but DockerSpawner can't affect the hub container, since it's already inside the hub container. That's why you need to set `--network jupyterhub`. To summarize:

- `--network jupyterhub` puts the *Hub* on the network
- `c.DockerSpawner.network_name = "juptyerhub"` puts single-user servers on the network

And these two need to match for them to be on the *same* network.
