### ISSUE TITLE
jupyterhub.dockerspawner.DockerSpawner' could not be imported

### ISSUE THREAD

**Issue by CraftHeart** [jupyterhub/dockerspawner#273]
i tried to use the dockerspawner, and i got got an error when i execute
"jupyterhub -f conf/jupyterhub_config.py". the output is
[C 2018-11-03 20:50:05.710 JupyterHub application:90] Bad config encountered during initialization: [C 2018-11-03 20:50:05.710 JupyterHub application:91] The 'spawner_class' trait of <jupyterhub.app.JupyterHub object at 0x7f53d9de4518> instance must be a type, but 'jupyterhub.dockerspawner.DockerSpawner' could not be imported

and i'am sure that i have installed dockerspawner, i execute pip3.5 install -e ./,
my jupyterhub version is 1.0,0.dev.

**Comment by sblack4** [comment]
I faced the same issue, see this issue on the jupyterhub repo: https://github.com/jupyterhub/jupyterhub/issues/1124 

It ended up that I simply hadn't installed it to the right python on my machine!

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo.

The issue is *almost* what `sblack4` suggests. The error is the same: a Spawner has been requested that is not installed. However, instead of dockerspawner not being in the env, the name of the Spawner has a typo: There is no `'jupyterhub.dockerspawner.DockerSpawner'`, instead dockerspawner is called `'dockerspawner.DockerSpawner'`. In recent versions of jupyterhub, you can use:

```python
c.JupyterHub.spawner_class = 'docker'
```

which is harder to mistype.


I'm going to close this one as stale/resolved. Feel free to open a new Issue if you are still having this trouble.
