### ISSUE TITLE
Merge the functionalities of SystemUserSpawner and SwarmSpawner

### ISSUE THREAD

**Issue by miguelmarco** [jupyterhub/dockerspawner#276]
Is it possible to get the functionality of SystemUserSpawner (that is, the container is run as a specific user, with his own -persistent- home directory available and maybe also acces to the rest of the home directories in case some other user shared a file with him) together with the SwarmSpawer (the jupyter server is run in any machine of the swarm)?

I guess one would need to inherit from both spawners, and maybe also tewak some methods, right?

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

I think it's hard for this combination to make a lot of sense in Swarm, since SystemUserSpawner makes a lot of assumptions about the host system and in swarm there are generally several host systems.

> I guess one would need to inherit from both spawners,

You could inherit from both, but it's going to be a little confusing. I would probably inherit from only SwarmSpawner and copy over the subset of relevant logic from SystemUserSpawner. It may even need some transformation to work in swarm.
