### ISSUE TITLE
timeouts pulling large docker images

### ISSUE THREAD

**Issue by robnagler** [jupyterhub/dockerspawner#293]
With large images, dockerspawner.pull_image times out:

```txt
Mar 15 05:01:42 v3.radia.run jupyterhub[8409]: [I 2019-03-15 05:01:42.877 JupyterHub dockerspawner:931] pulling image docker.io/radiasoft/beamsim-jupyter:dev
Mar 15 05:01:51 v3.radia.run jupyterhub[8409]: [W 2019-03-15 05:01:51.611 JupyterHub base:714] User vagrant is slow to start (timeout=10)
```

I know the timeout could be longer, but the image pull can take minutes especially in a test environment, but container startup is fast so a 10s timeout is reasonable for the (normal) case where the image doesn't need to be pulled.

Since jupyterhub.user.spawn doesn't really know what's going on, it might make sense to query the spawner for the status of the spawning instead of issuing an error. The spawner would be able to know what state it's in (pull_image, start_object, etc.), and then report back with more information (at a minimum).

I realize this is not a significant issue for most applications, but our images are over 8GB and they tend to grow a few 100MB every time we get a request for a new physics code.

**Comment by Koshmaar** [comment]
Hi @robnagler , we're also experiencing the timeouts for larger images. I'm curious, do you know, what are the settings for timeouts. We're based on https://github.com/jupyterhub/zero-to-jupyterhub-k8s/tree/7f6781e06b9199dfbd03fca72f4eb9b71044f394

Inside jupyterhub_config.py I set: 
```
c.KubeSpawner.start_timeout = 600
c.KubeSpawner.http_timeout = 600
```
But it had no effect. All that I see in hub log at the moment, is 
```I 2019-03-21 11:20:04.843 JupyterHub proxy:301] Checking routes```

And in browser on page of spawning notebook:
```2019-03-21 09:43:56+00:00 [Normal] Successfully pulled image "jupyterhub/k8s-network-tools:870725d"
2019-03-21 09:43:57+00:00 [Normal] Created container
2019-03-21 09:43:57+00:00 [Normal] Started container
2019-03-21 09:43:58+00:00 [Normal] pulling image "our_image"
Server requested <-------- here it restarts
2019-03-21 09:43:50+00:00 [Warning] pod has unbound PersistentVolumeClaims
2019-03-21 09:43:51+00:00 [Normal] Successfully assigned jupyter-user to minikube
```
Eventually the process finishes, as it seems docker is downloading layers, and remembers them. But if a layer is bigger than default timeout, then it might never finish. And it takes more time for re-downloading individual layers.

**Comment by robnagler** [comment]
Our timeouts have nothing to do with k8s. We are using a [custom dockerspawner](https://github.com/radiasoft/rsdockerspawner), which ends up [calling docker pull](https://github.com/jupyterhub/dockerspawner/blob/9c1efa0e396e4f2b9939fde7dacbe4187ceb4041/dockerspawner/dockerspawner.py#L932). JupyterHub [waits until spawner.start_timeout](https://github.com/jupyterhub/jupyterhub/blob/b1606f21e6afbcce6b9fd4bbdd07b29448a8f3f5/jupyterhub/user.py#L537), which is 60 seconds. The problem is that you don't always pull images so the start_timeout is widely variable: 10 seconds 99% of the time and 5 minutes (when the image is updated). The default pull_policy is fine, because we pull in advance on all our cluster nodes.

**Comment by minrk** [comment]
Setting `c.DockerSpawner.start_timeout` to 300 or 600 should work for this. Note that setting `http_timeout` should typically not need to be increased, because this is the time between start returning (a process should be running) and the server responding to http requests. A minute should be a very long wait for that to happen. Start, on the other hand, can take a long time.

Since DockerSpawner may pull images, we should probably override the default start_timeout to be 300 or similar (and do the same in KubeSpawner, which we have effectively done, but in , but setting this in your config ought to work. I spent a few minutes trying to make start_timeout longer for individual spawns only where image pulling is going to happen, but I realized that the timeout starts ticking before that information is known, so it wouldn't quite work.

**Comment by robnagler** [comment]
Thanks for the suggestion @minrk. Greatly appreciate the thorough explanation.

I would still like to vote splitting out the pull from the start, since they are quite different operations.

1.

**Comment by minrk** [comment]
That's going to be tricky, since jupyterhub doesn't have a generic `pull` stage. There is only start, stop, and poll. Most spawners do not use containers. The result is that pull kinda needs to be during start for Spawners that have pulling to do.

We could try to spawn a background pulling thread to ensure that the image is always up to date to reduce the likelihood of pull being needed on start.

**Comment by robnagler** [comment]
I appreciate the thoughts and suggestion. Our config mgmt system pulls automatically. We don't have custom images so it was only an issue before we added the pull.

I understand there are different spawners and containers/docker are special so don't do anything. The start_timeout adjustment should be good enough for most folks like me who have large containers.

**Comment by minrk** [comment]
It's conceivable that the discussion of enabling binder-like features in JupyterHub (e.g. image building) will result in a "prepare" stage that runs pre-start. If that happens, the new stage ought to have its own timeout and image pulling would logically belong there, I think.
