### ISSUE TITLE
Unexpected behaviour when logging out 

### ISSUE THREAD

**Issue by katsar0v** [jupyterhub/dockerspawner#309]
**Describe the bug**
I get the error
> docker.errors.APIError: 409 Client Error: Conflict (\"You cannot remove a running container 417a40d1034530fd06773e58ba210bdc3c724b375bbd6e80e920020561c8e558. Stop the container before attempting removal or force remove\"

**To Reproduce**
Not sure really how, happens when I logout in jupyterhub while using dockerspawner.

**Expected behavior**
Expecting the container to be removed, I set `remove_containers` to True (https://github.com/jupyterhub/dockerspawner/blob/0.9.1/dockerspawner/dockerspawner.py#L236)

**Additional context**
Hub version: 0.9.4
Dockerspawner: 0.9.1

I have jupyterhub running inside a docker container, which is using dockerspawner to spawn/remove another user containers. I could traceback the issue to:
`/opt/conda/lib/python3.6/site-packages/dockerspawner/dockerspawner.py` line 409

**Comment by ZelphirKaltstahl** [comment]
The error message seems rather weird. Why would one not be able to remove a Docker container? Using the Docker CLI, it is possible at any time to remove a container. So why would Python Docker API give such an error?

Could this be fixed by somehow handing in the equivalent of `--force` or `-f` of Docker CLI? Although this is not necessary with normal Docker CLI, maybe it is required with Python Docker API.

I think `remove_containers` expresses the intent to really remove containers on logout, so forcing the matter would be appropriate, as to not leave any containers alive.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. 409 errors should now be handled. Feel free to open a new Issue if you are still having this trouble.
