### ISSUE TITLE
how can we limit 1GPU per user ? so that a single user will not consume all the available GPU.

### ISSUE THREAD

**Issue by A1996KASH** [jupyterhub/dockerspawner#331]
how can we limit 1GPU per user ? so that a single user will not consume all the available GPU.

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

You can use device requests as described [here](https://github.com/docker/docker-py/pull/2471), for examle:

```python
c.DockerSpawner.extra_host_config = {
    "device_requests": [
        docker.types.DeviceRequest(
            count=1,
            capabilities=[["gpu"]],
        ),
    ],
}
```

**Comment by tunglambk** [comment]
Hi @minrk , I tried the config but all user use the same GPU. Is it possible for each user to be given a different GPU?

**Comment by minrk** [comment]
I think that's a docker question, since it would be the same for any docker container. It surprises me that docker's device request doesn't select available GPUs, but if that's the case, you may need to select with [device_ids](https://stackoverflow.com/questions/71429711/how-to-run-a-docker-container-with-specific-gpus-using-docker-sdk-for-python). But then apparently it's on you to keep track of which gpus are available.

**Comment by tunglambk** [comment]
Hi @minrk ,
As I understand, `extra_host_config` is applied for all containers so if I config device id in this configuration, all containers will use the same GPU. Is it right?
