### ISSUE TITLE
Pre-install required packages but Spawn timeout

### ISSUE THREAD

**Issue by ansoncsh** [jupyterhub/dockerspawner#335]
Hi,

I am using **pre_spawn_hook** to get different projects by request and **c.DockerSpawner.volumes** is used to mount the volume.
I want to pre-install required python packages based on **requirements.txt** from the project.

I customized a docker image to run **pip install -r requirements.txt** before starting the notebook server. However, I get the Spawn timeout error after 30s.

Any suggestion how to handle it?

Thank you!

**Comment by minrk** [comment]
Hi! I’m going through and cleaning up old/stale issues on this repo. Sorry for not responding in a reasonable amount of time!

I’m especially closing old “how to” questions to keep the Issues list to bug reports and feature requests. These can be directed to [the Jupyter forum](http://discourse.jupyter.org) if still relevant.

Pre_spawn_hook doesn't count toward the spawn timeout, so that duration is unlikely to be the issue. You can also use increase `c.Spawner.start_timeout` if it really is a time issue. However, spawn timeout is often a symptom of the server not starting at all, or not starting at the right URL, etc. Try to check the logs of the docker container (`jupyter-username`), and possibly add `--debug` to jupyterhub to see more logs.
