### ISSUE TITLE
How do I pass docker run args to spawned container

### ISSUE THREAD

**Issue by vincenzon** [jupyterhub/dockerspawner#344]
In order to use gdb in a container the user's container needs to have these docker run parameters passed: 

--cap-add=SYS_PTRACE --security-opt seccomp=unconfined

I tried: 

c.Spawner.extra_host_config = {"cap-add": "SYS_PTRACE", "security-opt": "seccomp=unconfined"}

In my jupyterhub_config.py but that didn't work for me. Is there a way to do this?

**Comment by manics** [comment]
`extra_host_config` is passed to the Docker client method `create_host_config`:
https://github.com/jupyterhub/dockerspawner/blob/d1f27e2855d2cefbdb25b29cc069b9ca69d564e3/dockerspawner/dockerspawner.py#L904-L909

Can you try using the parameters from the Docker client docs?
https://docker-py.readthedocs.io/en/stable/api.html#docker.api.container.ContainerApiMixin.create_host_config

**Comment by vincenzon** [comment]
I looked at the args to create_host_config and changed my args to:

`c.Spawner.extra_host_config = {"cap_add": "SYS_PTRACE", "security_opt": ["seccomp=unconfined"]}
`

(underscores rather than dashes). I deleted the existing containers and down/up'd the docker-compose. But still the parameters aren't having effect:

`[adcbp5l@mcsfvldxtadb02 jupyterhub]$ docker inspect b43b91c3da2b | grep Cap
            "CapAdd": null,
            "CapDrop": null,
[adcbp5l@mcsfvldxtadb02 jupyterhub]$ docker inspect b43b91c3da2b | grep Sec
            "SecurityOpt": null,
`

@manics did I misunderstand what you were suggesting?

**Comment by vincenzon** [comment]
In the end this was the right setting in jupyterhub_config.py:

```c.DockerSpawner.extra_host_config = {"cap_add": "SYS_PTRACE", "security_opt": ["seccomp=unconfined"]}
```

I also got bit by not deleting the jupyterhub volume to force the new config to take over. 

Thanks for your help @manics.

**Comment by phockett** [comment]
For anyone who finds this page and wants to add Docker capabilities (i.e. `cap_add` args equivalent to command-line docker run, or as included in a compose file) but is working with the SwarmSpawner, I got this to work using `c.SwarmSpawner.extra_container_spec` rather than `c.SwarmSpawner.extra_host_config`. 

e.g. to add `NET_ADMIN`: 

```c.SwarmSpawner.extra_container_spec = { "cap_add": ["NET_ADMIN"] }```

If working this appears in the service specs under `CapabilityAdd`, for a quick check ` docker inspect <service> | grep Capability`.

This worked for me in 2023, with Jupyter Hub container build from v4.0.2 Docker Hub image (Python 3.10), with the current version of the Docker Spawner (v12.1.0) pulled from Pypi. (Docker v20.10.7.)

Disclaimer: I didn't thoroughly test any other options here, although it definitely didn't work with setting options via `c.SwarmSpawner.extra_host_config` - see the [API docs for more](https://jupyterhub-dockerspawner.readthedocs.io/en/latest/api/index.html#dockerspawner.SwarmSpawner.extra_container_spec).
