### ISSUE TITLE
Controlling the size of volumes created with dockerspawner

### ISSUE THREAD

**Issue by magli184** [jupyterhub/dockerspawner#392]
Hi all,
I am relatively new to jupyterhub and dockerspawner, and are trying to it setup internally in our organization, to expose some notebooks to some end users who have limited python skills. 
In that regards I am using the proposed default solution with a mounted volume for each user's container. 
However, I was asked how we could limit the size of these volumes on the host machine. Such that a user can't fill up the host machine by writing large files to the disk.

I can't seem to figure out a good way to do this?

### Proposed change

A "default" way to limit/control the size of the mounted volumes in the singleuser containers. 

### (Optional): Suggest a solution

Similarly to how we can set a limit on the container's memory and cpu usage, I would like to have a way to control the size of the volumes, to avoid users filing up the host machine with large data files.

**Comment by manics** [comment]
Hi @magli184 
This is definitely something that would be nice to have, but it'll have to be done on the Docker side, DockerSpawner can't enforce storage quotas on it's own. I'm closing this issue since there's nothing we can do here, but please feel free to continue the discussion on the [Jupyter Community Forum](http://discourse.jupyter.org/) if you wish.
