### ISSUE TITLE
After a user has spawned, the container name is fixed even after changing prefix

### ISSUE THREAD

**Issue by cnydw** [jupyterhub/dockerspawner#437]
### Bug description
With `dockerspawner==12.1.0`, after a user `abc` has successfully spawned with container name `jupyter-abc`, the container name  `jupyter-abc` will always be used in the future. Updating `c.DockerSpawner.prefix` or `c.DockerSpawner.escape` in `jupyterhub_config.py` and restarting jupyterhub wouldn't affect the user `abc` anymore.

### Explanation

1. User `abc` spawns the container for the first time, the container name `jupyter-abc` is stored to `state["object_name"]` , user `abc` then stops the container. https://github.com/jupyterhub/dockerspawner/blob/a4625a1d34c15e18abb766db1becf89f80eece13/dockerspawner/dockerspawner.py#L910
2. Update `c.DockerSpawner.prefix` in the config file and restart jupyterhub. `load_state()` from https://github.com/jupyterhub/jupyterhub/blob/4ad9af583285e8cc9c8c1e455aca09ae3c21828c/jupyterhub/user.py#L362 runs when initializing the user objects, hence fetching the previous `object_name` from the database and store it to the user's spawner object.  https://github.com/jupyterhub/dockerspawner/blob/a4625a1d34c15e18abb766db1becf89f80eece13/dockerspawner/dockerspawner.py#L902
3. The user spawns the container again, the old container name is used.

### Solution

Maybe implementing the `clear_state()` method to clear `state["object_name"]` when the container stops, see 
https://github.com/jupyterhub/dockerspawner/blob/a4625a1d34c15e18abb766db1becf89f80eece13/dockerspawner/dockerspawner.py#L1401

**Comment by minrk** [comment]
Should be fixed by #447. Implementing `clear_state` is usually only needed if a Spawner maintains its own internal 'state' object, rather than reconstructing state on all `get_state`, which DockerSpawner does. The issue was failing to clear `object_id` which is meant to indicate that an object with that id exists, however, it's not cleared in `stop()`.

`object_name` _should_ however take precedence from state over config if the container is only stopped instead of removed (DockerSpawner.remove=False)
