### ISSUE TITLE
Interesting link in singleuser container

### ISSUE THREAD

**Issue by organizedkaos** [jupyterhub/dockerspawner#507]
Not sure if this is a bug or not but I was wondering what this link here is for?

https://zoom.us/my/jovyan?pwd=<omitted>

I found this link in files nested in the conda > site packages > jupyter*.

3.1 and 3.11 site package directories is where it is located and they appear in a couple of files.  Is this hardcode link needed for functionality?

**Comment by minrk** [comment]
> Is this hardcode link needed for functionality?

No, it is in documentation metadata for a package, not related to functionality.

Closing the issue since it's not related to this package, but I assume you mean the link in the jupyter-server README, whose origin is [here](https://github.com/jupyter-server/jupyter_server/blob/e7c0f331d4cbf82eb1a9e9bc6c260faabda0255a/README.md?plain=1#L50) and is a link to where community meetings are held for that package and related projects.
