### ISSUE TITLE
Request for image pull secrets to be passed for docker spawner single user image

### ISSUE THREAD

**Issue by Harushii18** [jupyterhub/dockerspawner#516]
### Proposed change

I would like for the api to provide a way to pass image pull secrets if you have a registry that you are pulling the image from. When deployed, the single user image pulls only when the user is logged in and in that case, credentials are needed or the image has to exist already for it to reference it. I would like an automatic pulling where the credentials are passed in through jupyterhub itself, much like how kubespawner has a similar implementation via the imagePullSecrets variable.

### Who would use this feature?

Anyone whose single user notebook img exists in a private registry upon deployment.

**Comment by manics** [comment]
Docker credentials are effectively global- once you've run `docker login` any Docker client can use those credentials. In Kubernetes access to the secret is explicit.

For this reason I think it'd be easier and clearer to have a startup script that runs [`docker login`](https://docs.docker.com/engine/reference/commandline/login/) before starting JupyterHub, rather than building it into DockerSpawner.

If you really wanted to do it in JupyterHub I think you could add the following to your `jupyterhub_config.py` file:
```py
import docker
client = docker.APIClient()
client.login(...)
```
https://docker-py.readthedocs.io/en/stable/api.html#docker.api.daemon.DaemonApiMixin.login

**Comment by Harushii18** [comment]
I see, thank you, I will try it out and see if it fixes my issue

**Comment by Harushii18** [comment]
@manics I added the startup script as you suggested with the docker login command, as well as other container registry login commands, and it worked perfectly, thank you!
